/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and mutation functions.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.25.4.
 * To regenerate, run `npx convex dev`.
 * @module
 */

// This file will be populated by the Convex CLI